### ISSUE TITLE
Redirect sends HTML page

### ISSUE THREAD

**Issue by bt90** [nosduco/nforwardauth#19] opened 2023-08-11 20:38 UTC
The initial redirect sends the whole login page with it:

![grafik](https://github.com/nosduco/nforwardauth/assets/1926175/bb04c85d-c514-4c59-9aad-099f7f4aad0a)

**Comment by nosduco** [comment] 2023-08-15 21:06
Interesting.. should only send on a GET request. Could you describe how to reproduce this? Thanks so much.

**Comment by nosduco** [comment] 2023-08-16 03:38
Potentially fixed by #27 ?

**Comment by bt90** [comment] 2023-08-16 05:17
> Potentially fixed by #27 ?

Good catch.

I'm using the network monitor tab of the developer console(F12) in Firefox/Chrome to check the requests and responses. Make sure to tick the `Preserve log` (Chrome) or `Enable persistent logs` (Firefox) checkbox. Otherwise the log gets cleared after a redirect.

**Comment by nosduco** [comment] 2023-08-17 02:31
I enabled "Preserve log" on Firefox but was not able to reproduce it.

**Closed** 2023-08-17 04:37 UTC
Labels: question
